### ISSUE TITLE
Throwing exception incase if the value is not present for the field

### ISSUE THREAD

**Issue by worldofprasanna** [KaushikNeelichetty/dynamodbtocsv#3]
If the value is not present for the field, it is panicing with,
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13f6173]

goroutine 1 [running]:
main.printValues(0xc0015c7c00, 0x73, 0x73, 0xc0001700f0, 0x3, 0x3)
	/home/travis/gopath/src/github.com/KaushikNeelichetty/dynamodbtocsv/main.go:95 +0x4c3
main.doFirstScan(0x7ffeefbff1c1, 0x15, 0x7ffeefbff1da, 0x1a, 0x0, 0x0, 0xc00000c0b8, 0xc0001700f0, 0x3, 0x3, ...)
	/home/travis/gopath/src/github.com/KaushikNeelichetty/dynamodbtocsv/main.go:48 +0x102
main.main()
	/home/travis/gopath/src/github.com/KaushikNeelichetty/dynamodbtocsv/main.go:32 +0x154
```

But I was expecting it to have empty string.

**Comment by KaushikNeelichetty** [comment]
Thanks for raising this issue @worldofprasanna :) 

I have pushed the fix and made a release.
